#!/bin/sh
ADDON_NAME=hap-homematic
HAPDIR=/usr/local/addons/hap-homematic/node_modules/hap-homematic/
HAPROOT=/usr/local/addons/hap-homematic/
CONFIG_URL=/addons/hap-homematic/index.html
CONFIG_DIR=/usr/local/etc/config
ADDONCFG_DIR=${CONFIG_DIR}/addons/${ADDON_NAME}
PIDFILE=/var/run/hap-homematic.pid 
VER=0.0.14
EXEC=node
EXECARGS=$HAPDIR/index.js

do_start()
{
	# run installer if needed
  	if [ -e $ADDONCFG_DIR/etc/postinstall.sh ];then
	  $ADDONCFG_DIR/etc/postinstall.sh
	fi
	start-stop-daemon --start --quiet --oknodo --make-pidfile --background  --pidfile $PIDFILE --exec $EXEC $EXECARGS
	logger -t homematic -p user.info "start hap-homematic"
}

do_stop()
{
    start-stop-daemon --stop --quiet  --oknodo  --retry 5  --pidfile $PIDFILE

    if [ -e $PIDFILE ];then
      rm -f $PIDFILE
    fi
  	
	sleep 2
	pgrep -f '^hap-homematic-.*' | xargs kill -9
	logger -t homematic -p user.info "stopped hap-homematic"
}


case "$1" in
  ""|start)

	do_start
	
	;;

  stop)
	
	do_stop
	
	;;

  restart)
  	
	do_stop
	sleep 10
	do_start
	
	;;

  info)
	echo "Info: <center><b>HomeKit HomeMatic</b><p style='margin-top: 5px;margin-bottom: 5px;'><img src='../addons/hap-homematic/hap-homematic-logo.png'></p></center>Homematic goes Apple Homekit<br /><a href='https://github.com/thkl/hap-homematic/'>https://github.com/thkl/hap-homematic/</a>"
	echo "Name: HomeKit HomeMatic"
	echo "Version: $VER"
	echo "Operations: uninstall restart"
	echo "Config-Url: $CONFIG_URL"
	echo "Update: /addons/${ADDON_NAME}/update-check.cgi"
	;;

  uninstall)
	logger -t homematic -p user.info "removing hap-homematic"
	kill -KILL $PSPID 2>/dev/null
	node /usr/local/addons/hap-homematic/node_modules/hap-homematic/etc/hm_addon.js hap
	rm -R /usr/local/addons/hap-homematic/
    rm /usr/local/etc/config/rc.d/hap-homematic 
	rm -R /usr/local/etc/config/addons/www/hap-homematic
	rm -R /usr/local/etc/config/addons/hap-homematic

	# remove the monit settings if there are leftovers
	if [ -f /usr/local/etc/monit_hap-homematic.cfg ]; then
	  rm /usr/local/etc/monit_hap-homematic.cfg
	  # and reload the monit
	  /usr/bin/monit reload
	fi 

	;;

  *)
	echo "Usage: $0 {start|stop|restart|uninstall}" >&2
	exit 1
	;;
esac

exit 0