#!/bin/sh
ADDON_NAME=hap-homematic
HAPDIR=/usr/local/addons/hap-homematic/node_modules/hap-homematic/
HAPROOT=/usr/local/addons/hap-homematic/
CONFIG_URL=/addons/hap-homematic/index.html
CONFIG_DIR=/usr/local/etc/config
PIDFILE=/var/run/hap-homematic.pid 
VER=0.0.11
PSPID=`ps -o pid,comm,args | awk '{if ($2=="node" && $4 ~ /hap-homematic/){print $1}}'`
PSPID2=`ps -o pid,comm,args | awk '{if ($2=="hap-homematic-c"){print $1}}'`
case "$1" in
  ""|start)

	# run installer if needed
  	$HAPROOT/etc/postinstall.sh

	if [ "$PSPID" = "" ]
	then
	  node $HAPDIR/index.js >/dev/null & echo $! >${PIDFILE}
	  logger -t homematic -p user.info "started hap-homematic"
	fi
	;;

  stop)
  	if [ "$PSPID" != "" ]
  	then
	  kill $PSPID >/dev/null
	  sleep 2
	  kill $PSPID2 >/dev/null
	  logger -t homematic -p user.info "stopped hap-homematic"
	  rm -f ${PIDFILE}
	fi
	;;

  restart)
  	if [ "$PSPID" != "" ]
  	then
	  kill $PSPID >/dev/null
	  sleep 2
	  kill $PSPID2 >/dev/null
	  logger -t homematic -p user.info "stopped hap-homematic"
	  rm -f ${PIDFILE}
	fi
	#wait 10 seconds until the configuration service will close
	sleep 10
	node $HAPDIR/index.js >/dev/null & echo $! >${PIDFILE}
	logger -t homematic -p user.info "started (restart) hap-homematic"
	;;

  info)
	echo "Info: <center><b>HomeKit HomeMatic</b><p style='margin-top: 5px;margin-bottom: 5px;'><img src='../addons/hap-homematic/hap-homematic-logo.png'></p></center>Homematic goes Apple Homekit<br /><a href='https://github.com/thkl/hap-homematic/'>https://github.com/thkl/hap-homematic/</a>"
	echo "Name: HomeKit HomeMatic"
	echo "Version: $VER"
	echo "Operations: uninstall restart"
	echo "Config-Url: $CONFIG_URL"
	echo "Update: /addons/${ADDON_NAME}/update-check.cgi"
	;;

  uninstall)
	logger -t homematic -p user.info "removing hap-homematic"
	kill -KILL $PSPID 2>/dev/null
	node /usr/local/addons/hap-homematic/node_modules/hap-homematic/etc/hm_addon.js hap
	rm -R /usr/local/addons/hap-homematic/
    rm /usr/local/etc/config/rc.d/hap-homematic 
	rm -R /usr/local/etc/config/addons/www/hap-homematic
	rm -R /usr/local/etc/config/addons/hap-homematic

	# remove the monit settings if there are leftovers
	if [ -f /usr/local/etc/monit_hap-homematic.cfg ]; then
	  rm /usr/local/etc/monit_hap-homematic.cfg
	  # and reload the monit
	  /usr/bin/monit reload
	fi 

	;;

  *)
	echo "Usage: $0 {start|stop|restart|uninstall}" >&2
	exit 1
	;;
esac

exit 0