#!/bin/sh

ADDONNAME=hap-homematic
CONFIG_DIR=/usr/local/etc/config
ADDON_DIR=/usr/local/addons/${ADDONNAME}
ADDONWWW_DIR=/usr/local/etc/config/addons/www
ADDONCFG_DIR=${CONFIG_DIR}/addons/${ADDONNAME}
RCD_DIR=${CONFIG_DIR}/rc.d

# make sure this addon is only executed on
# supported platforms

if [ "$1" == "HM-RASPBERRYMATIC" ]  || [ "$1" == "CCU3" ] ; then

mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
  mount /usr/local
fi
# remove the index file if there is one so the postinstall will run again
if [ -f ${ADDON_DIR}/node_modules/hap-homematic/index.js ]; then
  rm ${ADDON_DIR}/node_modules/hap-homematic/index.js
fi
# create necessary directories
mkdir -p ${ADDON_DIR}
chmod 755 ${ADDON_DIR}
mkdir -p ${RCD_DIR}
chmod 755 ${RCD_DIR}

# remove the old www stuff
if [ -f ${ADDONWWW_DIR}/${ADDONNAME}/ ]; then
  rm ${ADDONWWW_DIR}/${ADDONNAME}/*
  rmdir ${ADDONWWW_DIR}/${ADDONNAME}
fi

# copy addon
mkdir -p ${ADDONCFG_DIR}/etc
mkdir -p ${CONFIG_DIR}/${ADDONNAME}

# copy startup script
cp -af rc.d/* ${RCD_DIR}
# copy installer
cp -af hap/etc/postinstall.sh ${ADDONCFG_DIR}/etc
chmod +x ${ADDONCFG_DIR}/etc/postinstall.sh

#build system launcher
chmod +x ${RCD_DIR}/${ADDONNAME}
chmod +x ${ADDONWWW_DIR}/${ADDONNAME}/update-check.cgi

sync

#check if the plugin is allready installd 
if [ ! -f ${ADDON_DIR}/node_modules/hap-homematic/index.js ]; then
# new installation so reboot and the launcher will install the rest of the system
  exit 10
else
#so we have an update here and there is no need to reboot the Rasberrymatic will exit without an reboot
  exit 0
fi

fi
