#!/bin/sh

ADDONNAME=hap-homematic
CONFIG_DIR=/usr/local/etc/config
ADDON_DIR=/usr/local/addons/${ADDONNAME}
ADDONWWW_DIR=/usr/local/etc/config/addons/www
RCD_DIR=${CONFIG_DIR}/rc.d

# make sure this addon is only executed on
# supported platforms

if [ "$1" == "HM-RASPBERRYMATIC" ]  || [ "$1" == "CCU3" ] ; then

mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
  mount /usr/local
fi

# create necessary directories
mkdir -p ${ADDON_DIR}
chmod 755 ${ADDON_DIR}
mkdir -p ${RCD_DIR}
chmod 755 ${RCD_DIR}

# copy addon
mkdir -p ${ADDON_DIR}/etc
mkdir -p ${CONFIG_DIR}/${ADDONNAME}

#create the www stuff
mkdir -p ${ADDONWWW_DIR}/${ADDONNAME}
cp -af hap/etc/www/index.html ${ADDONWWW_DIR}/${ADDONNAME}
cp -af hap/etc/www/update-check.cgi ${ADDONWWW_DIR}/${ADDONNAME}

# copy startup script
cp -af rc.d/* ${RCD_DIR}

#build system launcher
chmod +x ${RCD_DIR}/${ADDONNAME}
chmod +x ${ADDONWWW_DIR}/${ADDONNAME}/update-check.cgi

mount -o remount,rw /
mkdir -p /usr/local/addons/npm/
#create new .npm cause /root/.npm is not writable
echo "cache=/usr/local/addons/npm/.npm" > /root/.npmrc
echo "init-module=/usr/local/addons/npm/.npm-init.js" >> /root/.npmrc
echo "userconfig=/usr/local/addons/npm/.npmrc" >> /root/.npmrc
echo "path=/usr/local/addons/npm/.npm" >> /root/.npmrc
mount -o remount,ro /


cd ${ADDON_DIR}
npm install ${ADDONNAME}

#create the button in system control
node ${ADDON_DIR}/node_modules/${ADDONNAME}/etc/hm_addon.js hap ${ADDON_DIR}/node_modules/${ADDONNAME}/etc/hap_addon.cfg

#run this
${RCD_DIR}/${ADDONNAME} start

fi

sync
exit 0