#!/bin/sh

ADDONNAME=hap-homematic
CONFIG_DIR=/usr/local/etc/config
ADDON_DIR=/usr/local/addons/${ADDONNAME}
RCD_DIR=${CONFIG_DIR}/rc.d

# make sure this addon is only executed on
# supported platforms

if [ "$1" == "HM-RASPBERRYMATIC" ]; then

mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
  mount /usr/local
fi

# create necessary directories
mkdir -p ${ADDON_DIR}
chmod 755 ${ADDON_DIR}
mkdir -p ${RCD_DIR}
chmod 755 ${RCD_DIR}

# copy addon
mkdir -p ${ADDON_DIR}/etc
mkdir -p ${CONFIG_DIR}/hap-homematic

cp -af hap/etc/* ${ADDON_DIR}/etc

# copy startup script
cp -af rc.d/* ${RCD_DIR}

#build system launcher
chmod +x ${RCD_DIR}/hap-homematic

#make postinstall executable / will launch via rc.d
chmod +x ${ADDON_DIR}/etc/postinstall.sh


fi

# synchronize filesystem before performing a reboot
# afterwards
sync
